name: Test Latest Tag Retrieval

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-latest-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Retrieve the latest tag
        id: get_tag
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "No tags found")
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Output the latest tag
        run: |
          echo "The latest tag is: ${{ env.LATEST_TAG }}"
